apiVersion: v1
kind: Pod
metadata:
  name: identity-server
  labels:
   tier: backend
   name: identity-server
spec:
  containers:
    - name: identity-server
      image: riyadennis/identity-server:latest
      ports:
        - containerPort: 8090
      env:
        - name: REST_PORT
          value: "8090"
        - name: ISSUER
          value: "open source"
        - name: KEY_PATH
          value: "/var/folders/"
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
              optional: false
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: host
              optional: false
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
              optional: false
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: port
              optional: false
        - name: MIGRATION_PATH
          value: "/home/webuser/migrations"
